### ISSUE TITLE
trying to compile master branch

### ISSUE THREAD

**Issue by avilella** [dpryan79/bison#2]
git clone --recursive https://github.com/dpryan79/bison
cd bison
make

git clone --recursive https://github.com/dpryan79/bison
Initialized empty Git repository in /bi/home/rocks-av/bison/.git/
remote: Counting objects: 511, done.
remote: Total 511 (delta 0), reused 0 (delta 0), pack-reused 511
Receiving objects: 100% (511/511), 194.40 KiB, done.
Resolving deltas: 100% (373/373), done.
Submodule 'htslib' (https://github.com/samtools/htslib.git) registered for path 'htslib'
Initialized empty Git repository in /bi/home/rocks-av/bison/htslib/.git/
remote: Counting objects: 6404, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 6404 (delta 21), reused 0 (delta 0), pack-reused 6365
Receiving objects: 100% (6404/6404), 5.50 MiB | 3.38 MiB/s, done.
Resolving deltas: 100% (4134/4134), done.
Submodule path 'htslib': checked out '94d13ce0d780780140c913459a5f7ad2e0d680a0'
[rocks-av@rocks1 ~]$ cd bison
[rocks-av@rocks1 bison]$ make
make -C htslib
make[1]: Entering directory `/bi/home/rocks-av/bison/htslib'
gcc -g -Wall -O2 -I. -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -I. -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -I. -c -o kstring.o kstring.c
gcc -g -Wall -O2 -I. -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -I. -c -o faidx.o faidx.c
In file included from faidx.c:33:
htslib/faidx.h:94: error: wrong number of arguments specified for ￃﾢﾀﾘ__deprecated__ￃﾢﾀﾙ attribute
make[1]: *** [faidx.o] Error 1
make[1]: Leaving directory `/bi/home/rocks-av/bison/htslib'
make: *** [HTSlib] Error 2

Any ideas?

**Comment by dpryan79** [comment]
Odd, this is an htslib issue. If you just clone/compile it do you get a similar error?

**Comment by avilella** [comment]
It compiles fine in my laptop with a newer version of gcc, so I am assuming
that's the issue. Can't run it on my laptop, since it's a virtualbox, and I
am not sure I can pretend to have 5 nodes on a VM for mpiexec...

**Comment by dpryan79** [comment]
Yeah, trying to simulate 5 (or even 3) nodes inside a VM doesn't sound like a fruitful thing to do.

Perhaps you can just modify `htslib/htslib/hts_defs.h` to have the following on line 94:

    #define HTS_DEPRECATED(x) __attribute__ ((__deprecated__))

Allegedly some older versions of gcc don't pass a character array to `__deprecated__`.

**Comment by dpryan79** [comment]
I'm going to go ahead and close this issue, since it's really an interaction between an outdated gcc and htslib.
