### ISSUE TITLE
latest release

### ISSUE THREAD

**Issue by 0xaf1f** [dpryan79/bison#5]
Your latest tagged version is from October 2014. It would help us to know that we're using a stable version (as opposed to an intermediate point in development) and when to update our installation if we could rely on the release tags.

Thanks for your consideration and thanks also for freely providing this software.

**Comment by dpryan79** [comment]
Oops, sorry about that! I've tagged 0.4.0 so you can get it as a proper release.

**Comment by 0xaf1f** [comment]
Great! Thank you.
